# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: po-conno <po-conno@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/19 12:52:56 by po-conno          #+#    #+#              #
#    Updated: 2015/06/19 14:25:08 by po-conno         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = ft_graphics
SOURCES = ft_graphics.ml
LIBS = graphics
OCAMLMAKEFILE = ~/Projects/Ocaml/OCamlMakefile
include $(OCAMLMAKEFILE)